/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';

// ---------------------------------------------------------------------------
// usePhysicalKeyboardDetection
// ---------------------------------------------------------------------------

type PhysicalKeyboardResult = {
  hasPhysicalKeyboard: boolean;
};

/**
 * Detects whether a physical (hardware) keyboard is present by listening for
 * trusted keydown events. A trusted event is one generated by the user agent
 * (i.e. from real hardware), not programmatically dispatched. Fixes
 * hermes-webui #3076.
 */
export function usePhysicalKeyboardDetection(): PhysicalKeyboardResult {
  const [hasPhysicalKeyboard, setHasPhysicalKeyboard] = useState(false);

  useEffect(() => {
    if (hasPhysicalKeyboard) return;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.isTrusted) {
        setHasPhysicalKeyboard(true);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [hasPhysicalKeyboard]);

  return { hasPhysicalKeyboard };
}

// ---------------------------------------------------------------------------
// useComposerKeyHandler
// ---------------------------------------------------------------------------

type ComposerKeyHandlerOptions = {
  /** Called when the composer should send the current message. */
  onSend: () => void;
  /** When true, pressing plain Enter sends the message. */
  sendOnEnter: boolean;
  /** Whether a physical (hardware) keyboard has been detected. */
  hasPhysicalKeyboard: boolean;
};

/**
 * Returns a keydown event handler for a message composer input.
 *
 * Key behaviour:
 * - Shift+Enter  → inserts a newline (no send).
 * - Ctrl/Cmd+Enter → always sends.
 * - Plain Enter  → sends only when `sendOnEnter` is true OR a physical
 *   keyboard has been detected; otherwise inserts a newline.
 */
export function useComposerKeyHandler(
  options: ComposerKeyHandlerOptions
): (event: React.KeyboardEvent<HTMLElement>) => void {
  const optionsRef = useRef(options);

  useEffect(() => {
    optionsRef.current = options;
  }, [options]);

  return useCallback((event: React.KeyboardEvent<HTMLElement>) => {
    const { onSend, sendOnEnter, hasPhysicalKeyboard } = optionsRef.current;

    if (event.key !== 'Enter') return;

    // Shift+Enter → newline, never send.
    if (event.shiftKey) return;

    // Ctrl/Cmd+Enter → always send.
    if (event.ctrlKey || event.metaKey) {
      event.preventDefault();
      onSend();
      return;
    }

    // Plain Enter → send when explicitly configured or physical keyboard present.
    if (sendOnEnter || hasPhysicalKeyboard) {
      event.preventDefault();
      onSend();
    }
  }, []);
}
